### ISSUE TITLE
remove .gitignore

### ISSUE THREAD

**Issue by nickdesaulniers** [mdn/content-kit-template#3]
rather than providing a git config that simply ignores *.swp files produced by vim, users should use a global git ignore file.  ex. 

[~/.gitconfig](https://github.com/nickdesaulniers/dotfiles/blob/master/.gitconfig#L10-L11)
[~/.gitignore_global](https://github.com/nickdesaulniers/dotfiles/blob/master/.gitignore_global)

**Comment by chrisdavidmills** [comment]
Removed .gitignore. Are you saying I should add the two above files too?

**Comment by nickdesaulniers** [comment]
No, those can be added to your personal $HOME directory, or the the contributor who add the .gitignore could do this, rather than commiting a .gitignore to the project.
